// <auto-generated />
namespace exam_db.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addAll_8_10 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addAll_8_10));
        
        string IMigrationMetadata.Id
        {
            get { return "201908101618237_addAll_8_10"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
