// <auto-generated />
namespace exam_db.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class updateReportTableToAdd_ConstantId_ForigenKey : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateReportTableToAdd_ConstantId_ForigenKey));
        
        string IMigrationMetadata.Id
        {
            get { return "201908070731516_updateReportTableToAdd_ConstantId_ForigenKey"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
