//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Global {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Global() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("exam_db.Resources.Global", typeof(Global).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t have an account?.
        /// </summary>
        public static string dont_have_account {
            get {
                return ResourceManager.GetString("dont_have_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgotten your password?.
        /// </summary>
        public static string Forgotten_password {
            get {
                return ResourceManager.GetString("Forgotten_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you have an account?.
        /// </summary>
        public static string have_account {
            get {
                return ResourceManager.GetString("have_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello There!.
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic.
        /// </summary>
        public static string Lang_Ar {
            get {
                return ResourceManager.GetString("Lang_Ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string Lang_En {
            get {
                return ResourceManager.GetString("Lang_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About us.
        /// </summary>
        public static string Menu_About {
            get {
                return ResourceManager.GetString("Menu_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Menu_Home {
            get {
                return ResourceManager.GetString("Menu_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please sign in to continue..
        /// </summary>
        public static string Please_login {
            get {
                return ResourceManager.GetString("Please_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please sign up to continue..
        /// </summary>
        public static string Please_sign_up {
            get {
                return ResourceManager.GetString("Please_sign_up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string Search_Filter_All {
            get {
                return ResourceManager.GetString("Search_Filter_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final.
        /// </summary>
        public static string Search_Filter_Final {
            get {
                return ResourceManager.GetString("Search_Filter_Final", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Midterm.
        /// </summary>
        public static string Search_Filter_Midterm {
            get {
                return ResourceManager.GetString("Search_Filter_Midterm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search For Exams, Quizs and others...
        /// </summary>
        public static string Search_Placeholder {
            get {
                return ResourceManager.GetString("Search_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up.
        /// </summary>
        public static string Sign_up {
            get {
                return ResourceManager.GetString("Sign_up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign out.
        /// </summary>
        public static string UserMenu_Logout {
            get {
                return ResourceManager.GetString("UserMenu_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Profile.
        /// </summary>
        public static string UserMenu_Profile {
            get {
                return ResourceManager.GetString("UserMenu_Profile", resourceCulture);
            }
        }
    }
}
