//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Homepage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Homepage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("exam_db.Resources.Homepage", typeof(Homepage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to College requirement.
        /// </summary>
        public static string College_requirement {
            get {
                return ResourceManager.GetString("College_requirement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Courses Categories.
        /// </summary>
        public static string Courses_Categories {
            get {
                return ResourceManager.GetString("Courses_Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to add Files.
        /// </summary>
        public static string Drag_Drop_Hint {
            get {
                return ResourceManager.GetString("Drag_Drop_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag &amp;amp; Drop Files Here or.
        /// </summary>
        public static string Drag_Drop_p1 {
            get {
                return ResourceManager.GetString("Drag_Drop_p1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string Drag_Drop_p2 {
            get {
                return ResourceManager.GetString("Drag_Drop_p2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to upload files.
        /// </summary>
        public static string Drag_Drop_p3 {
            get {
                return ResourceManager.GetString("Drag_Drop_p3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Searches.
        /// </summary>
        public static string Recent_Searches {
            get {
                return ResourceManager.GetString("Recent_Searches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Upload.
        /// </summary>
        public static string Title_File_Upload {
            get {
                return ResourceManager.GetString("Title_File_Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Page.
        /// </summary>
        public static string Title_Homepage {
            get {
                return ResourceManager.GetString("Title_Homepage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommended.
        /// </summary>
        public static string Title_Recommended {
            get {
                return ResourceManager.GetString("Title_Recommended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to University requirement.
        /// </summary>
        public static string University_requirement {
            get {
                return ResourceManager.GetString("University_requirement", resourceCulture);
            }
        }
    }
}
